language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -q -y qstat intltool cmake
  - echo 'install libminizip-dev from ubuntu vivid if current release is older than vivid:'
  - echo 'c2V0IC14CgojIGlmIHJlbGVhc2Ugb2xkZXIgdGhhbiB2aXZpZCAoMTUuMDQpCmlmIFsgIiQobHNiX3JlbGVhc2UgLXNyIHwgY3V0IC1jMS0yKSIgLWx0ICcxNScgXQp0aGVuCgogICAgIyBhZGQgdml2aWQgcmVwb3NpdG9yeSAobGlibWluaXppcC1kZXYgaXMgc2hpcGVkIGluIHVuaXZlcnNlKQogICAgZWNobzE9Ii9ldGMvYXB0L3NvdXJjZXMubGlzdC5kL3VidW50dS12aXZpZC1tYWluLmxpc3QiCgogICAgZWNobyAiZGViIGh0dHA6Ly9hcmNoaXZlLnVidW50dS5jb20vdWJ1bnR1IHZpdmlkIG1haW4gdW5pdmVyc2UiID4+ICR7ZWNobzF9CgogICAgIyBwaW4gdml2aWQgcmVwb3NpdG9yeSB0byBkaXNhYmxlIHBhY2thZ2UgaW5zdGFsbGF0aW9uIGZyb20gdGhpcyByZXBvc2l0b3J5IGJ5IGRlZmF1bHQKICAgIGVjaG8yPSIvZXRjL2FwdC9wcmVmZXJlbmNlcy5kL3ZpdmlkLXBpbm5pbmciCgogICAgZWNobyAiUGFja2FnZTogKiIgPj4gJHtlY2hvMn0KICAgIGVjaG8gIlBpbjogcmVsZWFzZSBuPXZpdmlkIiA+PiAke2VjaG8yfQogICAgZWNobyAiUGluLVByaW9yaXR5OiAtMTAwIiA+PiAke2VjaG8yfQoKICAgICMgYWRkIHRoZSB2aXZpZCByZXBvc2l0b3J5IGtleQogICAgYXB0LWtleSBhZHYgLS1yZWN2LWtleXMgLS1rZXlzZXJ2ZXIga2V5c2VydmVyLnVidW50dS5jb20gM0I0RkU2QUNDMEIyMUYzMgoKICAgICMgdXBkYXRlIHRoZSByZXBvc2l0b3JpZXMKICAgIGFwdC1nZXQgdXBkYXRlIC1xcQoKICAgICMgaW5zdGFsbCBsaWJtaW5pemlwLWRldiAoYW5kIGRlcGVuZGVuY2llcykgZnJvbSB2aXZpZAogICAgYXB0LWdldCBpbnN0YWxsIC15IC1xIC10IHZpdmlkIGxpYmdlb2lwLWRldiBsaWJtaW5pemlwLWRldiBnZXR0ZXh0CmZpCg==' | base64 -d | sudo -s

script:
  - cmake -DWITH_QSTAT=/usr/bin/quakestat .
  - make

notifications:
  irc: "chat.freenode.net#xqf"
  on_success: change
  on_failure: always
