language: c

compiler:
  - clang
  - gcc

before_install:
  - sudo -s scripts/travis_update_packages.sh

script:
  - cmake -DWITH_QSTAT=/usr/bin/quakestat .
  - make

notifications:
  irc: "chat.freenode.net#xqf"
  on_success: change
  on_failure: always
